[package]
name = "char"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "A fast, minimal text editor inspired by vim."
repository = "https://github.com/rhemab/char"
readme = "README.md"
keywords = ["cli", "terminal", "tui", "editor", "ratatui"]

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.0"
ropey = "1.6.1"
syntect = "5.3.0"

[profile.release]
codegen-units = 1 
lto = true 
opt-level = 3 
strip = true 

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
